name: mkbsd

on:
  push:
  #schedule:
  #- cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mkbhd:
    name: download
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
            repository: 'korewaChino/mkbsd-rs'

      - name: Get datetime
        id: datetime
        run: echo "datetime=$(date +'%Y%m%dT%H%M%S%z' --utc)" >> $GITHUB_OUTPUT
            
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - run: |
          cd /home/runner/work/mkbsd-rs-actions/mkbsd-rs-actions/target/debug
          ./mkbsd-rs
      - run: 7z -v1500m a -mx=0 downloads.7z downloads/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloads.7*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.datetime.outputs.datetime }}
          draft: false
          prerelease: false
          makeLatest: true
